### ISSUE TITLE
Missing US cities

### ISSUE THREAD

**Issue by PrimordialHelios** [dr5hn/countries-states-cities-database#2]
I noticed that the United States is missing a list of cities. Is there any chance you'll add them? If not, would you be able to recommend somewhere I could easily get a list to programmatically add to the list?

**Comment by dr5hn** [comment]
> I noticed that the United States is missing a list of cities. Is there any chance you'll add them? If not, would you be able to recommend somewhere I could easily get a list to programmatically add to the list?

Thanks for heads up on that.
Yes, i will add them. With that need your little bit of help to find out which cities are missing.

Here are some links having all states & cities of US. can you please verify and let me know which one is correct, complete & perfect. so that i will incorporate the updates in this repo.

https://gist.github.com/Lwdthe1/81818d30d23f012628aac1cdf672627d
https://github.com/cschoi3/US-states-and-cities-json/blob/master/data.json
https://gist.github.com/ahmu83/38865147cf3727d221941a2ef8c22a77
https://gist.github.com/djsaun/155af91592b087cb65b123599c0fe705

**Comment by PrimordialHelios** [comment]
Awesome, thanks!

I'm not sure if it's perfect, but [this one](https://github.com/cschoi3/US-states-and-cities-json/blob/master/data.json) certainly is the most complete out of the four you linked.

**Comment by dr5hn** [comment]
@PrimordialHelios Done. Updated.

Please verify it once. So that i can close this issue.

**Comment by PrimordialHelios** [comment]
Looks good! Thanks so much for the help!
