### ISSUE TITLE
Working with sql/world.sql on postgres

### ISSUE THREAD

**Issue by johannww** [dr5hn/countries-states-cities-database#210]
I have made some adaptations on 'sql/world.sql' to work on postgres. 

It seems to work. If you wish, I can fork the repo, perform more tests and offer a pull request.

Johann.

**Comment by dr5hn** [comment]
Hi @johannww,

That's awesome 🎉 Really appreciated it.

Since world.sql gets updated every time I fix the issues. Is there any way we can automate the conversion via Github action or script?

Moreover, please raise a PR and also if you can explain a process of conversion. I can easily figure out the way to automate it.

Thank you so much.

**Comment by dr5hn** [comment]
@johannww 

Thanks, Mahn!! You're Awesome 🤩
This is really helpful. Gonna run some tests on the script and patch it with Github Actions.

Again Many Thanks.

**Comment by bregoh** [comment]
@dr5hn did you make postgresql work?

**Comment by dr5hn** [comment]
@bregoh No.. not yet maybe i will take up next week...

**Comment by dschinkel** [comment]
@[johannww](https://github.com/johannww)
You save me a TON of work, thanks a TON.

**Comment by dr5hn** [comment]
I found a good source that can make your work easier, it works for most fields. But not for some.

https://sqlizer.io/

**Comment by dr5hn** [comment]
#564

**Comment by dr5hn** [comment]
Postgre DB is now Added! Yay! 🎉
