### ISSUE TITLE
Wrong data

### ISSUE THREAD

**Issue by andreafdaf** [dr5hn/countries-states-cities-database#229]
Hi, so far I've found those errors in the data:
- Brazil -> Rio de Janeiro -> "Armação dos Búzios" is the correct one, "Armação de Búzios" is a duplicate with an incorrect name
- Italy -> Lombardy -> "Scanzo-Rosciate" is misspelled, the correct name is "Scanzorosciate"
- Italy -> All states (in Italy they are called "regions") -> There are a lot of "Provincia di ..." but provinces are an intermediate administrative area between regions and cities, so they shouldn't be on the same list as cities. You should either create another nesting level (but it would mess with the structure of this list, so...) or remove them.

Anyway, thanks a lot for this list, this kind of data is really hard to find!

**Comment by crocco95** [comment]
Hi, I am encountering the same issue, in Italy, we have just 21 "states" called "Regions" (or in Italian "Regioni").

In this Wikipedia page you can find them all https://en.wikipedia.org/wiki/Regions_of_Italy , I can provide you the complete list formatted in JSON if you need 😃

**Comment by dr5hn** [comment]
@crocco95 Gotcha, But...

As @andreafdaf Said

> Italy -> All states (in Italy they are called "regions") -> There is a lot of "Provincia di ..." but provinces are an intermediate administrative area between regions and cities, so they shouldn't be on the same list as cities. You should either create another nesting level (but it would mess with the structure of this list, so...) or remove them.

There needs to be another intermediate nesting level to manage the Administrative divisions between regions and cities.

This is something I don't think it's possible.

My thoughts: I would rather clean up the states properly and put Administrative in cities table? Will that gonna work?

**Comment by crocco95** [comment]
I appreciate your fast response and I got your point. In my opinion, in Italy, the province is very similar to the concept of the city because of its geographical extension and population.
In the general discussion, the province is intended as a city containing a principal city with the same name as the province and really small cities with few people. For example, "The province of Bologna" has inside "Bologna" and other minor cities with many less population.

Also, many provinces are now presented as states and cities (es. the province of Ferrara is inside cities but the province of La Spezia is inside states), so I suggest putting them all as cities and putting just regions as states.

I remain very open minded about this discussion and my intension is just improve the already beautiful API so I can use it as best in the project I'm working at. :)

**Comment by dr5hn** [comment]
@crocco95 On the official ISO website it is displayed under country as subdivisions. https://www.iso.org/obp/ui/#iso:code:3166:IT

Looking at this, I realized if I am moving provinces to cities then the cities attached to that province will also need modifications. And that will become a huge update which I don't want because many users are using this way only.

So instead of moving the things here and there, I would simply be adding the `category` column in states which will justify it.

What do you think?

**Comment by crocco95** [comment]
Hi @dr5hn , sorry for the delay but I was on summer vacation.
I think your solution it's actually good! Thanks for your patience.
