### ISSUE TITLE
Huntingwood and Eagle_Farm cities are missing in Australia.

### ISSUE THREAD

**Issue by Shashi-GS** [dr5hn/countries-states-cities-database#385]
Hi,

Could you please update the DB with these cities of Australia.

Huntingwood, 2148  NSW (https://en.wikipedia.org/wiki/Huntingwood,_New_South_Wales)
Eagle Farm, 4009  QLD (https://en.wikipedia.org/wiki/Eagle_Farm,_Queensland)

--
Thanks,
Shashi

**Comment by Shashi-GS** [comment]
@dr5hn , 
in our service it is not listing out these cities. 
![image](https://user-images.githubusercontent.com/17082069/158734799-58f0ccfa-f3e4-4d2a-a7a8-deaf47ac37a7.png)

However, I tried in your site (https://dr5hn.github.io/countries-states-cities-database/) I am able to see that. 
--
Thanks,
Shashi

**Comment by dr5hn** [comment]
@Shashi-GS 
![Screenshot 2022-03-17 at 10 32 49 AM](https://user-images.githubusercontent.com/6929121/158740705-5b3632b8-e72c-40e5-ae2f-96372447591d.png)

**Comment by Shashi-GS** [comment]
Thanks for the response. But this issue is marked as closed. I thought it is deployed as a service already.  is my understanding is wrong?

**Comment by dr5hn** [comment]
@Shashi-GS Yes, since this is a DB repository and the Database issue has been resolved. I have marked it as closed.

Issues and deployments are separate things, On the decided deployment date whatever will be latest will be deployed directly on the production. Of course, it will contain your data so I don't need to keep a track of it anyway.
