### ISSUE TITLE
Change Dialect to Postgres

### ISSUE THREAD

**Issue by dschinkel** [dr5hn/countries-states-cities-database#432]
I can't run this for a Postgres DB.  Any ideas on how to transform this to Postgres Dialect so that I can run the `.sql`?

**Comment by AykutBuyukkaya** [comment]
@dschinkel 
Hi, I encountered the same problem when I started to work with this data. One solution is to insert those data to a MYSQL database and then migrate the database to Postgres using tools like pgloader. I couldn't do that, however. I encountered some errors due to my postgres version. Another solution is you can create a JSON reader for your project and parse the given JSON data and it is straightforward. Just read the JSON data and save each entity into the database.

**Comment by MaybeThisIsRu** [comment]
My solution isn't very general so I can't share it here, but I wrote a Django management command to take the JSON files as the input (instead of SQL), and create a new table row for each JSON entity.

**Comment by dr5hn** [comment]
@MaybeThisIsRu @AykutBuyukkaya @dschinkel I found a good source that can make your work easier, it works for most fields. But not for some.

https://sqlizer.io/

**Comment by dr5hn** [comment]
Duplicate of #210
