### ISSUE TITLE
The restful api not display the coordinates attached

### ISSUE THREAD

**Issue by 5ylvino** [dr5hn/countries-states-cities-database#471]
Is there a proper way of call the api to display the full details on each country down to their are coordinates, which is very important to me along their names? 

##currently from restful api
```
[
    {
        "id": 1,
        "name": "Afghanistan",
        "iso2": "AF"
    },
```

##expected
```
[ {
	"isoCode": "IN",
	"name": "India",
	"phonecode": "91",
	"flag": "🇮🇳",
	"currency": "INR",
	"latitude": "20.00000000",
	"longitude": "77.00000000",
	"timezones": [
		{
			"zoneName": "Asia\/Kolkata",
			"gmtOffset": 19800,
			"gmtOffsetName": "UTC+05:30",
			"abbreviation": "IST",
			"tzName": "Indian Standard Time"
		}
	]
}
```

**Comment by 5ylvino** [comment]
i guess i have seen it that i have to call them individual to get the detail afterwards. Thanks

**Comment by 5ylvino** [comment]
I discovered that of the city details on coordinates are not display and there is no sample on how to get it on the doc

**Comment by dr5hn** [comment]
@5ylvino Yes, you're correct that I am not showing coordinates on city API. For 2 reasons
1. Since cities request spits a lot of data, so to make it lightweight have only added basic info to API.
2. Reason I have not added city details API is people start leeching the data making server hung up!


Even if I add it in near future, I will make that route paid.
