### ISSUE TITLE
Cities lists are incorrect

### ISSUE THREAD

**Issue by ZigZapps** [dr5hn/countries-states-cities-database#5]
I've noticed that there are plenty of cities are incorrect, lots of duplicated and added from other countries just check the json file for: "Zirakpur" for example.

**Comment by ZigZapps** [comment]
I just found another incorrect/duplicated cities. the list has lots of incorrect data. please fix the issue.. Thanks

**Comment by ZigZapps** [comment]
please bear in mind these issues are with the exported json files

**Comment by PrimordialHelios** [comment]
I recently noticed this too. I'll try and go through today and figure out which cities are wrong.

**Comment by ZigZapps** [comment]
I think the cities in the DB tables are correct, but the exported json files have incorrect data.

**Comment by dr5hn** [comment]
@PrimordialHelios @ZigZapps 
Appreciate your research into library. Will also take a look to make table and jsons synchronized correctly.

**Comment by dr5hn** [comment]
@PrimordialHelios @ZigZapps

I figured out the issue. The issue was in my JSON exporting PHP script.
https://github.com/dr5hn/countries-states-cities-database/commit/ce2cbbe1365bcd322d4f4fabc2ad52c77117d725
https://github.com/dr5hn/countries-states-cities-database/commit/f3063bccdf9ac76293dd144f3c677220c0dfb928

Removed Duplicates & Rectified JSONs updated. 

Appreciate your efforts. Thanks.

**Comment by paulpierre** [comment]
Cities are still wrong, there are Italian cities duplicated in multiple countries in the JSON file, about 843 of them. Please look at how often "Acquaviva delle Fonti" repeats for example in the states of Korea "Kyeongsangbuk" it is repeated
![Screen Shot 2019-06-26 at 1 12 30 PM](https://user-images.githubusercontent.com/142327/60200380-027c9e00-9814-11e9-9744-ed77162b517e.png)
