### ISSUE TITLE
US is returning 66 states but it should return only 50 states

### ISSUE THREAD

**Issue by Andrey-dash** [dr5hn/countries-states-cities-database#704]
The United States has only 50 states but it returns 66 states.

Sample (index.js):
```
const { State } = require('country-state-city')

console.log(State.getStatesOfCountry('US').map((p) => p.name).length)
```

This is the list that is currently returning:
`['Alabama', 'Alaska', 'American Samoa', 'Arizona', 'Arkansas', 'Baker Island', 'California', 'Colorado', 'Connecticut', 'Delaware', 'District of Columbia', 'Florida', 'Georgia', 'Guam', 'Hawaii', 'Howland Island', 'Idaho', 'Illinois', 'Indiana', 'Iowa', 'Jarvis Island', 'Johnston Atoll', 'Kansas', 'Kentucky', 'Kingman Reef', 'Louisiana', 'Maine', 'Maryland', 'Massachusetts', 'Michigan', 'Midway Atoll', 'Minnesota', 'Mississippi', 'Missouri', 'Montana', 'Navassa Island', 'Nebraska', 'Nevada', 'New Hampshire', 'New Jersey', 'New Mexico', 'New York', 'North Carolina', 'North Dakota', 'Northern Mariana Islands', 'Ohio', 'Oklahoma', 'Oregon', 'Palmyra Atoll', 'Pennsylvania', 'Puerto Rico', 'Rhode Island', 'South Carolina', 'South Dakota', 'Tennessee', 'Texas', 'United States Minor Outlying Islands', 'United States Virgin Islands', 'Utah', 'Vermont', 'Virginia', 'Wake Island', 'Washington', 'West Virginia', 'Wisconsin', 'Wyoming']`

**Comment by meek2100** [comment]
@Andrey-dash You need to look back in history at the colonial era where islands and other small land masses were just conquered by navy's and that out gunned the locals significantly. And then those land masses would be treated as capital to be gained or lost in wars and diplomatic agreements between the large civilized countries. 

The United States may only have 50 incorporated United "States", but you need to look at this as you pick a country and what state/province/territories are subject to each countries jurisdiction?  The USA has 50 incorporated United "States", but they also have 5 major territories, and several minor islands. The way to look at it is something like Puerto Rico, would you call that a country or a state/province/territories? 

The answer is that it is a state/province/territories, because it is not a sovereign nation so they can't claim to be a country. The United States along with Puerto Rico could chose to become an incorporated state or attempt to succeed from the United States at which point the US government would need to decide if we allow them leave or if we want to enforce our ownership leading to a war of some kind. For this and many other geopolitical reasons as well as internal US politics Puerto Rico has remained stuck as a territory.

There would actually be 67 truthfully, because Washington DC is both a City and a piece of land that falls outside of the jurisdiction of the United States it resides in and is governed by its own local government as well as the US government.

You can find more detail here: https://en.wikipedia.org/wiki/List_of_states_and_territories_of_the_United_States

**Comment by tacman** [comment]
DC pays taxes and sends citizens to war, yet has no federal representative in our house of representatives.  It could be called a "colony".  

But yes, the problem is really with the terminology, "state" also includes things like Washington, DC and Guam, thus 66.
