### ISSUE TITLE
Import Error world.sql

### ISSUE THREAD

**Issue by strongui** [dr5hn/countries-states-cities-database#761]
Trying to import the world.sql file into my PSQL DB and I get this: 

```
ERROR:  relation "public.subregions" does not exist 

SQL state: 42P01
```

**Comment by rhnatiuk** [comment]
@dosu-bot The answer is not helpful.

The problem is that psql/world.sql was dumped using pg_dump as a text dump, and it can be restored using psql only, not with pg_restore.

In the current psql/world.sql all tables/constraints/etc. are handled in alphabetic order (furthermore, the script tries to delete them without even checking if they exist, for example), and all tables are populated in alphabetic order (cities first) too. But those tables have foreign key constraints, so it won't work.

A possible solution would be to produce a psql/world.dump file using pg_dump instead of a textual dump so that it could be used with pg_restore. But then database version compatibility might become a problem...

**Comment by dr5hn** [comment]
One can dump sql file like this
```
    psql -U postgres -d postgres -f "/path/to/your/dump/world.sql"
```

**Comment by sushilbansal** [comment]
@rhnatiuk if you are running it for the first time then delete the initial few lines in sql file which are altering and dropping the tables.
