### ISSUE TITLE
Missing Surat, Rajkot, Bharuch and other Cities of Gujarat, India.

### ISSUE THREAD

**Issue by nimsabhaya** [dr5hn/countries-states-cities-database#79]
Missing very famous cities like Surat, Rajkot, Bharuch, etc of Gujarat State.

**Comment by dr5hn** [comment]
@nimsabhaya Thanks for reporting. Appreciate it. Will try to fix it ASAP.

**Comment by dr5hn** [comment]
@nimsabhaya The issue was Ambiguos characters in City Name
So `Rajkot` was `Rājkot`.
Hence you were unable to find it. Anyways fixed the encoding issue for all cities.

Due to this, I was able to add more cities to Gujarat :
Bagasara
Dahod
Dangs (India)
Delwada
Jalalpore
Jodia
Kavant
Khambhalia
Kutch district
Mandvi (Surat)
Mehsana
Morva (Hadaf)
Panchmahal district
Pavi Jetpur
Siddhpur
Thangadh
Vallabhipur
Vansda
Vaso
Vinchhiya
Wadhai
Wadhwan

**Comment by dr5hn** [comment]
@nimsabhaya Fixed in #81.
