### ISSUE TITLE
Turkey's biggest cities are not in the dataset

### ISSUE THREAD

**Issue by decodemyproject** [dr5hn/countries-states-cities-database#849]
For example, Antalya and Istanbul are missing. Two major cities that should definitely be there.

**Comment by dr5hn** [comment]
Fixed: https://github.com/dr5hn/countries-states-cities-database/commit/531c01e3a7819e13a8b26fbbba6ff4e4276cae3a

**Comment by oytunyuksel** [comment]
Hi,

I noticed a significant issue with the Turkey cities/districts data following recent changes. There are incorrect entries particularly related to Metropolitan Municipalities (Büyükşehir).

In Turkey's administrative structure, Metropolitan Municipalities (Büyükşehir Belediyesi) have a special status where:
1. The province and central district share the same name
2. The central district is not listed separately as it's administered under the metropolitan municipality

For example:
- "Antalya" should not appear as a district because it's a Metropolitan Municipality
- Same applies for "Istanbul" and other metropolitan cities

This was correctly structured in the previous version, but appears to have been broken after recent PR changes. The current structure doesn't accurately reflect Turkey's unique administrative system where metropolitan municipalities have different organizational structure than regular provinces.

I suggest reverting the recent PR that caused these changes to restore the correct administrative structure.

**Comment by decodemyproject** [comment]
For my take on the matter, while administratively it may be accurate not to list Antalya separately as a city, geographically, it makes sense to do so. Antalya is a well-known, distinct urban area, and omitting it could lead to confusion, especially for purposes like mapping, travel, or general geographical analysis. Personally, I use the cities dataset for geographical purposes so omitting Antalya and Istanbul as cities makes no sense in practical, real-world use. Geography matters just as much as governance structures in this regard.

**Comment by ChristianGreinke** [comment]
I agree with you.

decodemyproject ***@***.***> schrieb am Fr., 18. Okt. 2024,
00:08:

**Comment by oytunyuksel** [comment]
Hello,

While this approach might make sense for your use case, it's not correct to generalize it. For example, I live in Istanbul, and no one living within Istanbul's provincial borders would ever say "I'm going to Istanbul" because there isn't a district called "Istanbul" within Istanbul. The same applies to all metropolitan municipalities in Turkey.

Therefore, adding a non-existent district as if it exists is incorrect. If we're going to use the province and district data from this repo as a reference in any project, the data should reflect the official administrative structure. Even for geographical purposes, data that doesn't reflect the administrative structure can be misleading. For instance, it could lead to errors in address selection, official procedures, or local services.

The root issue stems from Turkey not having states, yet Istanbul appears as if it were a state-level entity. However, this isn't unique to Turkey - it's the same in all countries without states in this repo. The approach is based on the "administrative level" - in countries without states, the state area shows cities, and the city area shows districts. When you accept this structure, there's no problem.

If geographical usage is important, a separate "geographical_regions" or "urban_areas" dataset could be created. However, the current state/city structure must reflect the administrative organization accurately.

**Comment by ChristianGreinke** [comment]
Thank you for your explanation. Then I agree with you and we need to add
that marker.

Oytun Yüksel ***@***.***> schrieb am Fr., 18. Okt. 2024,
09:25:

**Comment by oytunyuksel** [comment]
Hi @dr5hn, can you revert this pr?

**Comment by decodemyproject** [comment]
Hi @oytunyuksel,

I understand your emphasis on accurately reflecting Turkey’s administrative structure, but I’d like to respectfully disagree with the idea that this is the best approach for the dataset’s broader use.  This dataset is likely being used by people who need a consistent way to reference cities across multiple countries. Listing major urban centers as cities, even when they are also administrative provinces, is a standard that makes data more intuitive and easier to work with for international users. If we strictly follow local administrative structures, it could make the dataset less accessible to users who aren’t deeply familiar with Turkey’s unique governance setup.

Also, many global data platforms and mapping services refer to Antalya and Istanbul as cities, take Google Maps as the most simplified example. 

I appreciate your suggestion of creating a separate dataset for "geographical regions" or "urban areas," but this could complicate things for users who just need a straightforward list of cities. Instead, why not include major urban areas like Antalya and Istanbul as cities, while still preserving the administrative classifications as an additional data point? This way, we maintain accuracy but also ensure that the data is practical and user-friendly.
