### ISSUE TITLE
City "Bavla" is missing of state "gujrat".

### ISSUE THREAD

**Issue by jeetsoni** [dr5hn/countries-states-cities-database#863]
"Bavla" city is missing in database, which come under state gujrat.

**Comment by jeetsoni** [comment]
@dosu, i have never done open source contrubution so i will be not able to solve this can you help me.

**Comment by mtsfer** [comment]
> @dosu, i have never done open source contrubution so i will be not able to solve this can you help me.

Actually you don't need to do what he is saying to contribute. As pointed in the contribution section of the readme, all you need to do is go to `sql/world.sql` file and edit it to add the record is missing. You can check some pull requests that add cities to the database, like #848, to have an idea how to do that.

But don't worry, you pointing the issue is already a great contribution and I'm sure that someone will fix this soon!
