### ISSUE TITLE
Safe to refer to items using their auto increment id (while inheriting future datasets)

### ISSUE THREAD

**Issue by Vimiso** [dr5hn/countries-states-cities-database#873]
Is it safe to refer to cities etc by their auto increment id? Or do future versions of the database get issued with new/missed cities slotted into some position resulting in a shift of all auto increments? Otherwise, are all new items always added to the end of any given dataset? Thanks.

**Comment by mtsfer** [comment]
New items are always added at the end of the dataset, so the chances of id colision is low.

**Comment by tin-cat** [comment]
Because this repository uses auto-incremental ids for their id fields, the id number assigned to each entry in the database is decided by the database engine, and it might hence correlate to specific and unknown characteristics in the systems used by the maintainers of this repository.

For example: A typical relational database assigns incremental ids based on the order the insert statements are issued: Different backup-restore software implementations, clustered database configurations or event-based architectures might produce different IDs for the same inputted data.

Because of this, it is my opinion that ids on this repository (at least the ids provided by the SQL dumps) should not be considered as stable nor used as references to entities (cities, countries, etc.) in your database.

Even though the IDs might be stable between releases, I don't think the maintainers can guarantee this unequivocally, specially because they might be changing methodologies, software stacks and internal procedures in the future that might very well affect this.

Instead, I would recommend using the ISO standard codes provided for entities like countries and states. These have been specifically created with standardization in mind, and, by design, will not change in the future. Despite, of course, real-world geopolitical changes occur, in which case I don't know how those ISO standards are designed to adapt while maintaining retro-compatibility, if any.

For cities, there is not -to my knowledge- any standardized ISO code or similar that is both complete and reliable. I'm investigating using the `wikiDataId` this repository provides, which seems to be reliable enough (here's some info on that: https://www.wikidata.org/wiki/Wikidata:Identifiers)

Hope this helps!
